# Generated by Django 3.2.5 on 2021-07-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210723_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
