# Generated by Django 3.1.5 on 2021-01-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210122_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='unnamed', max_length=100),
        ),
    ]
