# Generated by Django 3.2.5 on 2021-10-16 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^*{0,1}[0-9]{1,4}{0,1}[-\\s\\./0-9]*$', 'only valid phone numbers are required')]),
        ),
    ]
