# Generated by Django 3.2.8 on 2021-10-29 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_forgetpassswordrequests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForgetPassswordRequests',
            new_name='EmailRequest',
        ),
        migrations.AddField(
            model_name='friend',
            name='acceptance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
