# Generated by Django 3.2.8 on 2021-10-29 20:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_alter_newaccountactivationlinks_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewAccountActivationLinks',
            new_name='NewAccountActivationLink',
        ),
        migrations.RenameModel(
            old_name='EmailRequest',
            new_name='SendEmailRequest',
        ),
    ]
