# Generated by Django 3.2.4 on 2021-07-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
