# Generated by Django 3.2.5 on 2021-07-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_cover',
            field=models.ImageField(default='profile_covers/default_cover.jpg', upload_to='profile_covers'),
        ),
    ]
