# Generated by Django 3.2.12 on 2022-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220519_1848'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend',
            name='Unique_frienship',
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('side1', 'side2'), name='Unique_friendship'),
        ),
    ]
