# Generated by Django 3.2.12 on 2022-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220519_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'accepted'), (2, 'declined'), (3, 'waiting')], default=3),
        ),
    ]
