# Generated by Django 3.2.5 on 2021-07-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_profile_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
