# Generated by Django 3.2.12 on 2022-05-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_friendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[(1, 'accepted'), (2, 'declined'), (3, 'waiting')], default=3, max_length=10),
        ),
    ]
