# Generated by Django 3.2.12 on 2022-05-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_friendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('a', 'accepted'), ('b', 'declined'), ('c', 'waiting')], default='c', max_length=10),
        ),
    ]
