# Generated by Django 3.2.5 on 2021-07-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cover',
            field=models.ImageField(default='profile_covers/default.jpg', upload_to='profile_covers'),
        ),
    ]
