# Generated by Django 3.2.5 on 2021-08-23 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('C', 'Comment'), ('L', 'Like'), ('F', 'Friend')], max_length=1)),
                ('picture', models.ImageField(default='profile_pics/default.jpg', upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('route_id', models.SlugField(default=None)),
                ('seen', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('route_id', 'type', 'user_from')},
            },
        ),
    ]
