# Generated by Django 3.2.5 on 2021-07-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=''),
        ),
    ]
