# Generated by Django 3.2.5 on 2021-11-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('route_id', 'type', 'user_from'), name='notification_uniqueness_constraint'),
        ),
    ]
