# Generated by Django 3.2.5 on 2021-11-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_uniqueness_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_uniqueness_constraint',
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
    ]
