# Generated by Django 3.2.5 on 2021-07-20 16:11

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_notification_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.SlugField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('link', 'type', 'user_from')},
        ),
    ]
