# Generated by Django 3.2.5 on 2021-07-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210720_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.SlugField(default=None),
        ),
    ]
