# Generated by Django 3.2.5 on 2021-07-20 16:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_alter_notification_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='link',
            new_name='route_id',
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('route_id', 'type', 'user_from')},
        ),
    ]
